In [1]:
# pandas
import pandas as pd

In [2]:
import PySimpleGUI as sg
def selection(option):
    #sg.theme('DarkAmber')   # Add a touch of color
    #select the variable we want to calculate
    options = option

    # All the stuff inside your window.
    layout = [ 
            [sg.Text('Select one->'), sg.Listbox(options,select_mode=sg.LISTBOX_SELECT_MODE_SINGLE,size=(20,len(options)))],
            [sg.Button('Ok'), sg.Button('Cancel')]
        ]

    # Create the Window
    window = sg.Window('Make your choice', layout)

    # Event Loop to process "events" and get the "values" of the input
    while True:
        event, values = window.read()
        print( f"event={event}" )
        if event is None or event == 'Ok' or event == 'Cancel': # if user closes window or clicks cancel
            break
        
    # close  the window        
    window.close()

    if event == "Cancel":
        print( "You cancelled" )
    else:
        print('You entered ', values[0])
        sg.popup( f"You selected {values[0]}" )        
    return values

In [3]:
#list of databases NA
datanames = pd.read_excel("datanames.xlsx")
datanames

                                         description       datanames
0  National accounts aggregates by industry (up t...     nama_10_a64
1  Gross capital formation by industry (up to NAC...  nama_10_a64_p5
2  National accounts employment data by industry ...   nama_10_a64_e

In [4]:
#Put the number of the database
database_selection=2
#change the number to select another database
database_sel= datanames.iloc[database_selection]["datanames"]
database_sel

'nama_10_a64_e'

In [5]:
#nama_10_a64 National accounts aggregates by industry (up to NACE A*64)
#NAMA_10_A64_P5 Gross capital formation by industry (up to NACE A*64)
#National accounts employment data by industry (up to NACE A*64)

import eurostat
df = eurostat.get_data_df(database_sel, flags=False)
df

,unit,nace_r2,na_item,geo\time,2021,2020,2019,2018,2017,2016,...,1984,1983,1982,1981,1980,1979,1978,1977,1976,1975
0,PCH_PRE_HW,A,EMP_DC,AT,0.7,5.9,-3.3,-3.1,-1.7,-0.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,PCH_PRE_HW,A,EMP_DC,BE,-1.6,1.9,1.2,1.0,0.4,3.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PCH_PRE_HW,A,EMP_DC,BG,-5.6,-1.6,-4.5,-6.4,6.2,-3.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PCH_PRE_HW,A,EMP_DC,CH,-6.7,2.0,-10.8,-3.2,-4.0,-0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PCH_PRE_HW,A,EMP_DC,CY,0.2,-0.9,0.9,-5.7,-1.9,2.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43368,THS_PER,U,SELF_DC,SE,NaN,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43369,THS_PER,U,SELF_DC,SI,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43370,THS_PER,U,SELF_DC,SK,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43371,THS_PER,U,SELF_DC,UK,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43372,THS_PER,U,SELF_DC,XK,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.columns

Index([    'unit',  'nace_r2',  'na_item', 'geo\time',       2021,       2020,
             2019,       2018,       2017,       2016,       2015,       2014,
             2013,       2012,       2011,       2010,       2009,       2008,
             2007,       2006,       2005,       2004,       2003,       2002,
             2001,       2000,       1999,       1998,       1997,       1996,
             1995,       1994,       1993,       1992,       1991,       1990,
             1989,       1988,       1987,       1986,       1985,       1984,
             1983,       1982,       1981,       1980,       1979,       1978,
             1977,       1976,       1975],
      dtype='object')

In [7]:
#eliminate columns for years previous to 2011
years =[]
year_start=1975
year_study=2011
for y in range(year_start,year_study): 
    years.append(y)
df=df.drop(years, axis=1)#quitamos todas las columnas de añosque no nos interesan
#rename geo time column to be easier to handle because of the name
df.rename(columns={"geo\\time": "geo"}, inplace=True)
#We can get the unique values of the different variables

In [8]:
#list of selected variables variabales

dic_unit = eurostat.get_dic('unit') #dictionary for all the unit in eurostat
#print the units in the database
for u in df.unit.unique():
    if u in dic_unit:
        print (u + " -"+dic_unit[u])
#select the unit that we want
unit=selection(df.unit.unique())[0]

print(" ")

dic_item = eurostat.get_dic('na_item') #dictionary for all the unit in eurostat
for item in df.na_item.unique():
    if item in dic_item:
        print (item + " -"+dic_item[item])
naitem=selection(df.na_item.unique())[0]

print(" ")

#determine the variable of interest based on the selection
for item in naitem:
    if item in dic_item:
        variable_of_interest=dic_item[item]
variable_of_interest

PCH_PRE_HW -Percentage change on previous period (based on hours worked)
PCH_PRE_JOB -Percentage change on previous period (based on jobs)
PCH_PRE_PER -Percentage change on previous period (based on persons)
THS_HW -Thousand hours worked
THS_JOB -Thousand jobs
THS_PER -Thousand persons
event=Ok
You entered  ['THS_PER']

EMP_DC -Total employment domestic concept
SAL_DC -Employees domestic concept
SELF_DC -Self-employed domestic concept
event=Ok
You entered  ['EMP_DC']

'Total employment domestic concept'

In [9]:
nacedrop=['O','K66', 'J', 'H', 'C16-C18','A03', 'O-Q', 'E', 'C31-C33', 'M_N', 'J58-J60', 'R-U', 'G', 'K', 'TOTAL', 'L68A', 'A02', 'C22_C23', 'C29_C30',  'B-E', 'G-I', 'N', 'Q', 'R', 'C24_C25','C', 'M69-M71', 'M73-M75', 'U', 'S', 'B', 'M', 'A01', 'K65','K64']
countries_not_selected= ['UK', 'TR', 'AL','IS','LI','NO','CH','UK','ME','MK','AL','RS','TR','BA','EU28','EU15','EA','EA19','EA12']

#we select the rows that have the right unit, nace codes, items and countries
df_selection=df[df.unit.isin(unit)&~df.nace_r2.isin(nacedrop)&df.na_item.isin(naitem)&~df.geo.isin(countries_not_selected)]

In [10]:
#ratios to divide N80_82 and 31_32. Value Added from SBS
ratios_values = pd.read_excel("ratioCN-Persons employed - number.xlsx")
ratios_values.set_index('nace_r2', inplace=True)#nace como índice
ratios_values

,Persons employed - number2011,Persons employed - number2012,Persons employed - number2013,Persons employed - number2014,Persons employed - number2015,Persons employed - number2016,Persons employed - number2017,Persons employed - number2018,Persons employed - number2019
nace_r2,,,,,,,,,
C31,0.544241,0.539424,0.529556,0.523017,0.526568,0.523893,0.521526,0.513514,0.526316
C32,0.455759,0.460576,0.470444,0.476983,0.473432,0.476107,0.478474,0.486486,0.473684
N80,0.182240,0.181738,0.176900,0.169462,0.166770,0.168959,0.163414,0.160231,0.157301
N81,0.553512,0.548676,0.551854,0.552864,0.547135,0.549442,0.551335,0.561084,0.559926
N82,0.264248,0.269586,0.271246,0.277674,0.286095,0.281599,0.285251,0.278685,0.282773

In [11]:
weights_target = pd.read_excel("ecosystemweights.xlsx")
weights_target

,NACE_R2,Aerospace & Defence,Agri-food,Construction,Cultural and Creative Industries,Digital,Electronics,Energy - Renewables,Energy Intensive Industries,Health,Mobility - Transport - Automotive,"Proximity, Social Economy and Civil Security",Retail,Textile,Tourism
0,A,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,C10-C12,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,C13-C15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
3,C16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,C17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,C18,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,C19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,C20,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,C21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,C22,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,C23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,C24,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,C25,0.097362,0.066168,0.305189,0.008982,0.020901,0.019600,0.015553,0.036324,0.051639,0.235501,0.023466,0.044200,0.008535,0.036845
13,C26,0.440000,0.000000,0.000000,0.000000,0.222517,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,C27,0.230000,0.000000,0.000000,0.000000,0.000000,0.000000,0.378114,0.000000,0.000000,0.025089,0.000000,0.000000,0.000000,0.000000
15,C28,0.067894,0.078244,0.198393,0.012618,0.030525,0.122558,0.015984,0.040056,0.056225,0.277642,0.029954,0.057346,0.009986,0.050067
16,C29,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
17,C30,0.681044,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.318958,0.000000,0.000000,0.000000,0.000000
18,C31,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,C32,0.000000,0.000000,0.000000,0.079000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,C33,0.166456,0.118497,0.155381,0.013205,0.032879,0.015305,0.016405,0.047373,0.068633,0.165263,0.035659,0.064677,0.009670,0.071660
21,D,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.290000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,E36,0.017444,0.121809,0.102483,0.024670,0.022172,0.006887,0.011280,0.040057,0.110972,0.058200,0.076530,0.074141,0.012856,0.104587
23,E37-E39,0.027442,0.094801,0.136681,0.018941,0.027805,0.010187,0.014313,0.086234,0.085284,0.098157,0.053702,0.077560,0.014370,0.071190
24,F,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,G45,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
26,G46,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
27,G47,0.000000,0.000000,0.000000,0.012000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.155000,1.000000,0.000000,0.000000
28,H49,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.517742,0.000000,0.000000,0.000000,0.445221
29,H50,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.777240,0.000000,0.000000,0.000000,0.222225
30,H51,0.092866,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.907134
31,H52,0.178000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.393612,0.000000,0.000000,0.000000,0.000000
32,H53,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
33,I,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.140000,0.000000,0.000000,1.000000
34,J58,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35,J59_J60,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
36,J61,0.069000,0.000000,0.000000,0.000000,0.972721,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37,J62_J63,0.000000,0.000000,0.000000,0.004000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
38,L,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.083600,0.000000,0.000000,0.000000
39,M69_M70,0.024984,0.077210,0.115127,0.027735,0.051335,0.011667,0.009650,0.049054,0.087623,0.086191,0.057233,0.134521,0.011523,0.067615
40,M71,0.033689,0.060163,1.256805,0.173047,0.044230,0.014561,0.011725,0.036812,0.076141,0.092899,0.044152,0.080038,0.011156,0.054884
41,M72,0.056517,0.072081,0.104068,0.027198,0.069032,0.050716,0.008286,0.030642,0.142165,0.129971,0.046536,0.081408,0.011505,0.048453
42,M73,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
43,M74_M75,0.000000,0.000000,0.000000,0.640000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
44,N77,0.027148,0.082093,0.129191,0.029051,0.051669,0.013045,0.008469,0.031288,0.099961,0.085503,0.061228,0.126924,0.009894,0.082765
45,N78,0.027148,0.082093,0.129191,0.028451,0.051669,0.013045,0.008469,0.031288,0.099961,0.085503,0.061228,0.126924,0.009894,0.082765
46,N79,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
47,N80,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
48,N81,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.280000,0.000000,0.000000,0.000000
49,N82,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.110000,0.000000,0.000000,1.000000
50,P,0.000000,0.000000,0.000000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
51,Q86,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
52,Q87_Q88,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000
53,R90-R92,0.000000,0.000000,0.000000,0.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.660000
54,R93,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
55,S94,0.000000,0.000000,0.000000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
56,S95,0.000000,0.000000,0.000000,0.260000,0.480000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
57,S96,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
58,T,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000

In [12]:
weights_target.NACE_R2.unique()

array(['A', 'C10-C12', 'C13-C15', 'C16', 'C17', 'C18', 'C19', 'C20',
       'C21', 'C22', 'C23', 'C24', 'C25', 'C26', 'C27', 'C28', 'C29',
       'C30', 'C31', 'C32', 'C33', 'D', 'E36', 'E37-E39', 'F', 'G45',
       'G46', 'G47', 'H49', 'H50', 'H51', 'H52', 'H53', 'I', 'J58',
       'J59_J60', 'J61', 'J62_J63', 'L', 'M69_M70', 'M71', 'M72', 'M73',
       'M74_M75', 'N77', 'N78', 'N79', 'N80', 'N81', 'N82', 'P', 'Q86',
       'Q87_Q88', 'R90-R92', 'R93', 'S94', 'S95', 'S96', 'T'],
      dtype=object)

In [13]:
# columns of countries to be eliminated
cols = ['AT', 'BE', 'BG', 'CY', 'CZ', 'DE', 'DK', 'EE', 'EL', 'ES', 'FI','FR', 'HR', 'HU', 'IE', 'IT', 'LT','LU', 'LV', 'MT','NL', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK']

#create a dataframe for the results
results_compiled = pd.DataFrame()


import numpy as np
#loop to calculate values for years
for j in range (2011,2019):
    year=j
    #we transpose the values for the year selected
    for i in range (year,year+1):
        df_target = pd.pivot_table(df_selection, values=i, index=['nace_r2'],columns=["geo"], aggfunc=np.sum, fill_value=0)#reorde
    df_target['sum'] = df_target[cols].sum(axis=1)#sums the columns of the countries to "sum" 
    df_target=df_target.drop(cols, axis=1)#eliminamos las columnas sumadas de países
    df_target.loc[df_target['EU27_2020']==0,'EU27_2020'] = df_target['sum']#now we can locate columns with 0 and make the substitution with the column "sum"
    moddf_target=df_target.drop('sum', axis=1)#we create a new table 
    #add rows C31,... and assign value with the ratio multiplying by the value of position C31_32
    year_ratio=j-2011
    moddf_target.loc['C31'] = ratios_values.iloc[0][year_ratio]*moddf_target.loc['C31_C32','EU27_2020']
    moddf_target.loc['C32'] = ratios_values.iloc[1][year_ratio]*moddf_target.loc['C31_C32','EU27_2020']
    moddf_target.loc['N80'] = ratios_values.iloc[2][year_ratio]*moddf_target.loc['N80-N82','EU27_2020']
    moddf_target.loc['N81'] = ratios_values.iloc[3][year_ratio]*moddf_target.loc['N80-N82','EU27_2020']
    moddf_target.loc['N82'] = ratios_values.iloc[4][year_ratio]*moddf_target.loc['N80-N82','EU27_2020']
    #we eliminate rows C31_C32
    moddf_target = moddf_target.drop(['C31_C32', 'N80-N82'])
    pd.set_option('display.float_format', lambda x: '%.4f' % x)
    #cargamos los pesos en el dataframe weight  
    weights_target = pd.read_excel("ecosystemweights.xlsx")
    weights_target.set_index('NACE_R2', inplace=True)#nace como índice
    column_name=str(variable_of_interest)+str(year)
    weights_target[variable_of_interest]=weights_target.index.map(moddf_target['EU27_2020'])#busca en df_target el nace y copia el valor de EU27_2020 en la fila del nace the weights_target
    #creamos la matriz de resultados
    results=weights_target
    for i in range(0,14):
        results.iloc[:, i]=weights_target.iloc[:, i]*weights_target[variable_of_interest]#we multiply the total value added by the weight for each nace
    results.loc['total'] = results.select_dtypes(pd.np.number).sum() #we add the values of each colum in a row call total
    results_compiled[column_name]=results.loc['total']
results_compiled = results_compiled.drop(variable_of_interest)
#sum of the totals
results_SMEs = results_compiled.copy()  
results_big = results_compiled.copy()
#results_compiled.loc['total'] = results_compiled.select_dtypes(pd.np.number).sum()
results_compiled

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:38: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

,Total employment domestic concept2011,Total employment domestic concept2012,Total employment domestic concept2013,Total employment domestic concept2014,Total employment domestic concept2015,Total employment domestic concept2016,Total employment domestic concept2017,Total employment domestic concept2018
Aerospace & Defence,4079.8819,4100.1239,4080.6811,4091.5754,4122.4248,4236.4952,4285.8933,4357.0545
Agri-food,17321.1820,17209.1475,16925.8970,16880.2429,16639.1561,16333.1121,16434.7304,16314.2753
Construction,24623.1805,24185.1843,23807.1933,23936.6647,24100.3091,24472.5364,25023.3586,25713.1182
Cultural and Creative Industries,7853.3113,7818.9244,7799.5805,7876.0025,7878.6945,7989.3586,8062.0979,8152.6139
Digital,5740.0895,5833.4973,5892.0051,5998.0673,6146.9657,6307.0522,6526.7323,6779.8654
Electronics,1687.9330,1703.3110,1686.2614,1688.8865,1687.2306,1713.7850,1746.6744,1787.9573
Energy - Renewables,1132.0685,1128.7805,1123.7088,1137.0761,1132.4672,1151.5313,1154.9756,1175.4119
Energy Intensive Industries,7578.8540,7467.0502,7340.7426,7329.2732,7345.9468,7448.0386,7600.8864,7729.8497
Health,22307.4349,22497.6882,22772.8669,23157.4826,23562.5265,24079.1915,24548.8874,24988.9731
Mobility - Transport - Automotive,12883.4655,12895.0047,12880.9753,13066.2443,13289.0871,13618.0851,13968.8915,14314.9962
"Proximity, Social Economy and Civil Security",21152.9532,21317.9254,21446.9824,21740.4186,22100.9311,22505.6251,22868.7857,23242.1224
Retail,28857.5568,28786.1332,28468.7188,28647.4874,28926.6434,29181.3716,29497.6590,29703.7415
Textile,2578.3848,2527.2784,2447.6653,2445.5514,2404.9776,2389.0299,2406.3160,2387.2210
Tourism,17555.8578,17666.9491,17787.8213,18270.6045,18741.1280,19338.2354,19949.6639,20444.0270

In [14]:
#save to file
filename = "%s.xlsx" % variable_of_interest
results_compiled.to_excel(filename)

In [15]:
#KPI IN PERCENTAGES
#gross value added as % of total employmente
df_employment = eurostat.get_data_df('nama_10_a64_e', flags=False)
df_employment.rename(columns={"geo\\time": "geo"}, inplace=True)
df_employment.columns

Index([   'unit', 'nace_r2', 'na_item',     'geo',      2021,      2020,
            2019,      2018,      2017,      2016,      2015,      2014,
            2013,      2012,      2011,      2010,      2009,      2008,
            2007,      2006,      2005,      2004,      2003,      2002,
            2001,      2000,      1999,      1998,      1997,      1996,
            1995,      1994,      1993,      1992,      1991,      1990,
            1989,      1988,      1987,      1986,      1985,      1984,
            1983,      1982,      1981,      1980,      1979,      1978,
            1977,      1976,      1975],
      dtype='object')

In [16]:
#eliminate columns for years previous to 2011
years =[]
year_start=1975
year_study=2011
for y in range(year_start,year_study): 
    years.append(y)
years.append(2020)

df_employment=df_employment.drop(years, axis=1)


geo_employment=['EU27_2020']
unit_employment= ['THS_PER']
item_employment= ['EMP_DC']
nace_employment=['TOTAL']
#year_employment=[]
#for y in range(2011,2019): 
 #   year_employment.append(y)
df_employment_selection=df_employment[df_employment.nace_r2.isin(nace_employment)&df_employment.unit.isin(unit_employment)&df_employment.na_item.isin(item_employment)&df_employment.geo.isin(geo_employment)]

#drop columns of no interest
df_employment_selection=df_employment_selection.drop(['unit','na_item','nace_r2'], axis=1)

#set index in geo
df_employment_selection.set_index('geo', inplace=True)

#we need to reorder the columns in ascending order to match the other database
columns_employment_selection = df_employment_selection.columns
columns_employment_selection= columns_employment_selection.sort_values(ascending=True)
df_employment_selection = df_employment_selection.reindex(columns=columns_employment_selection)
df_employment_selection

,2011,2012,2013,2014,2015,2016,2017,2018,2019,2021
geo,,,,,,,,,,
EU27_2020,195946.0900,195470.2600,194714.3800,196492.3300,198323.0500,200895.9800,204145.3600,207134.1200,209449.8700,209294.2100

In [17]:
#we create a table to store the new values Gross Added Value as % of gdp
employment_percentage=results_compiled.copy()

num_col_result=len(results_compiled.columns)

#iteration to calculate the values
for i in range(0,num_col_result):
    employment_percentage.iloc[:,i]= results_compiled.iloc[:, i]*100/df_employment_selection .iloc[0, i]
employment_percentage=employment_percentage.add_suffix('-percentage total employment')
employment_percentage

,Total employment domestic concept2011-percentage total employment,Total employment domestic concept2012-percentage total employment,Total employment domestic concept2013-percentage total employment,Total employment domestic concept2014-percentage total employment,Total employment domestic concept2015-percentage total employment,Total employment domestic concept2016-percentage total employment,Total employment domestic concept2017-percentage total employment,Total employment domestic concept2018-percentage total employment
Aerospace & Defence,2.0821,2.0976,2.0957,2.0823,2.0786,2.1088,2.0994,2.1035
Agri-food,8.8398,8.8040,8.6927,8.5908,8.3899,8.1301,8.0505,7.8762
Construction,12.5663,12.3728,12.2267,12.1820,12.1520,12.1817,12.2576,12.4138
Cultural and Creative Industries,4.0079,4.0001,4.0057,4.0083,3.9727,3.9769,3.9492,3.9359
Digital,2.9294,2.9843,3.0260,3.0526,3.0995,3.1395,3.1971,3.2732
Electronics,0.8614,0.8714,0.8660,0.8595,0.8507,0.8531,0.8556,0.8632
Energy - Renewables,0.5777,0.5775,0.5771,0.5787,0.5710,0.5732,0.5658,0.5675
Energy Intensive Industries,3.8678,3.8200,3.7700,3.7301,3.7040,3.7074,3.7233,3.7318
Health,11.3845,11.5095,11.6955,11.7854,11.8809,11.9859,12.0252,12.0642
Mobility - Transport - Automotive,6.5750,6.5969,6.6153,6.6497,6.7007,6.7787,6.8426,6.9110
"Proximity, Social Economy and Civil Security",10.7953,10.9060,11.0146,11.0643,11.1439,11.2026,11.2022,11.2208
Retail,14.7273,14.7266,14.6208,14.5794,14.5856,14.5256,14.4493,14.3403
Textile,1.3159,1.2929,1.2571,1.2446,1.2127,1.1892,1.1787,1.1525
Tourism,8.9595,9.0382,9.1353,9.2984,9.4498,9.6260,9.7723,9.8699

In [18]:
#save to file

filename = "%s.xlsx" % (variable_of_interest+str('percentage total employment'))
employment_percentage.to_excel(filename)

In [19]:
#KPI IN PERCENTAGES

#create the new table and drop the first column
percent_change=results_compiled.copy() 
percent_change=percent_change.drop(results_compiled.columns[0], axis=1)

#calculate the new number of columns
num_col_percent=len(percent_change.columns)

#iteration to calculate the values
for i in range(0,num_col_percent):
    percent_change.iloc[:,i]= (results_compiled.iloc[:, i+1]-results_compiled.iloc[:, i])*100/results_compiled.iloc[:, i]
percent_change=percent_change.add_suffix('-percentage change')
percent_change

,Total employment domestic concept2012-percentage change,Total employment domestic concept2013-percentage change,Total employment domestic concept2014-percentage change,Total employment domestic concept2015-percentage change,Total employment domestic concept2016-percentage change,Total employment domestic concept2017-percentage change,Total employment domestic concept2018-percentage change
Aerospace & Defence,0.4961,-0.4742,0.2670,0.7540,2.7671,1.1660,1.6604
Agri-food,-0.6468,-1.6459,-0.2697,-1.4282,-1.8393,0.6222,-0.7329
Construction,-1.7788,-1.5629,0.5438,0.6837,1.5445,2.2508,2.7565
Cultural and Creative Industries,-0.4379,-0.2474,0.9798,0.0342,1.4046,0.9105,1.1227
Digital,1.6273,1.0030,1.8001,2.4824,2.6043,3.4831,3.8784
Electronics,0.9111,-1.0010,0.1557,-0.0980,1.5738,1.9191,2.3635
Energy - Renewables,-0.2904,-0.4493,1.1896,-0.4053,1.6834,0.2991,1.7694
Energy Intensive Industries,-1.4752,-1.6915,-0.1562,0.2275,1.3898,2.0522,1.6967
Health,0.8529,1.2231,1.6889,1.7491,2.1927,1.9506,1.7927
Mobility - Transport - Automotive,0.0896,-0.1088,1.4383,1.7055,2.4757,2.5760,2.4777
"Proximity, Social Economy and Civil Security",0.7799,0.6054,1.3682,1.6583,1.8311,1.6136,1.6325
Retail,-0.2475,-1.1027,0.6279,0.9745,0.8806,1.0839,0.6986
Textile,-1.9821,-3.1501,-0.0864,-1.6591,-0.6631,0.7236,-0.7935
Tourism,0.6328,0.6842,2.7141,2.5753,3.1861,3.1618,2.4781

In [20]:
#save to file

filename = "%s.xlsx" % (variable_of_interest+str('percentage change'))
percent_change.to_excel(filename)