In [1]:
# pandas
import pandas as pd

In [2]:
import PySimpleGUI as sg
def selection(option):
    #sg.theme('DarkAmber')   # Add a touch of color
    #select the variable we want to calculate
    options = option

    # All the stuff inside your window.
    layout = [ 
            [sg.Text('Select one->'), sg.Listbox(options,select_mode=sg.LISTBOX_SELECT_MODE_SINGLE,size=(20,len(options)))],
            [sg.Button('Ok'), sg.Button('Cancel')]
        ]

    # Create the Window
    window = sg.Window('Make your choice', layout)

    # Event Loop to process "events" and get the "values" of the input
    while True:
        event, values = window.read()
        print( f"event={event}" )
        if event is None or event == 'Ok' or event == 'Cancel': # if user closes window or clicks cancel
            break
        
    # close  the window        
    window.close()

    if event == "Cancel":
        print( "You cancelled" )
    else:
        print('You entered ', values[0])
        sg.popup( f"You selected {values[0]}" )        
    return values

In [3]:
#nama_10_a64 National accounts aggregates by industry (up to NACE A*64)
#NAMA_10_A64_P5 Gross capital formation by industry (up to NACE A*64)
#National accounts employment data by industry (up to NACE A*64)

import eurostat
df = eurostat.get_data_df('nama_10_nfa_st', flags=False)
df

,unit,nace_r2,asset10,geo\time,2021,2020,2019,2018,2017,2016,...,1984,1983,1982,1981,1980,1979,1978,1977,1976,1975
0,CLV15_MEUR,A,N111G,AT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CLV15_MEUR,A,N111G,BE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CLV15_MEUR,A,N111G,BG,NaN,NaN,2234.0,2027.9,1839.3,1668.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CLV15_MEUR,A,N111G,CY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CLV15_MEUR,A,N111G,CZ,NaN,328.3,318.6,302.7,292.7,283.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229753,PYR_MNAC,U,N11ON,NL,NaN,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229754,PYR_MNAC,U,N11ON,SE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229755,PYR_MNAC,U,N11ON,SI,NaN,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229756,PYR_MNAC,U,N11ON,SK,NaN,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229757,PYR_MNAC,U,N11ON,UK,NaN,NaN,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.columns

Index([    'unit',  'nace_r2',  'asset10', 'geo\time',       2021,       2020,
             2019,       2018,       2017,       2016,       2015,       2014,
             2013,       2012,       2011,       2010,       2009,       2008,
             2007,       2006,       2005,       2004,       2003,       2002,
             2001,       2000,       1999,       1998,       1997,       1996,
             1995,       1994,       1993,       1992,       1991,       1990,
             1989,       1988,       1987,       1986,       1985,       1984,
             1983,       1982,       1981,       1980,       1979,       1978,
             1977,       1976,       1975],
      dtype='object')

In [5]:
#eliminate columns for years previous to 2011
years =[]
year_start=1975
year_study=2011
for y in range(year_start,year_study): 
    years.append(y)
years.append(2020)
df=df.drop(years, axis=1)#quitamos todas las columnas de añosque no nos interesan
#rename geo time column to be easier to handle because of the name
df.rename(columns={"geo\\time": "geo"}, inplace=True)
#We can get the unique values of the different variables

In [6]:
asset= df.asset10.unique()
asset

array(['N111G', 'N111N', 'N112G', 'N112N', 'N1131G', 'N1131N', 'N11321G',
       'N11321N', 'N11322G', 'N11322N', 'N1132G', 'N1132N', 'N115G',
       'N115N', 'N1171G', 'N1171N', 'N1173G', 'N1173N', 'N117G', 'N117N',
       'N11G', 'N11KG', 'N11KN', 'N11MG', 'N11MN', 'N11N', 'N11OG',
       'N11ON'], dtype=object)

N111G -Dwellings (gross)
N111N -Dwellings (net)
N112G -Other buildings and structures (gross)
N112N -Other buildings and structures (net)
N1131G -Transport equipment (gross)
N1131N -Transport equipment (net)
N11321G -Computer hardware (gross)
N11321N -Computer hardware (net)
N11322G -Telecommunications equipment (gross)
N11322N -Telecommunications equipment (net)
N1132G -ICT equipment (gross)
N1132N -ICT equipment (net)
N115G -Cultivated biological resources (gross)
N115N -Cultivated biological resources (net)
N1171G -Research and development (gross)
N1171N -Research and development (net)
N1173G -Computer software and databases (gross)
N1173N -Computer software and databases (net)
N117G -Intellectual property products (gross)
N117N -Intellectual property products (net)
N11G -Total fixed assets (gross)
N11KG -Total Construction (gross)
N11KN -Total Construction (net)
N11MG -Machinery and equipment and weapons systems (gross)
N11MN -Machinery and equipment and weapons systems (net)
N11N -Total fixed assets (net)
N11OG -Other machinery and equipment and weapons systems (gross)
N11ON -Other machinery and equipment and weapons systems (net)

In [7]:
dic_asset = eurostat.get_dic('asset10') #dictionary for all the unit in eurostat
dic_asset

{'N1N': 'Produced non-financial assets (net)',
 'N1ON': 'Fixed assets and inventories (net)',
 'N11N': 'Total fixed assets (net)',
 'N11KN': 'Total Construction (net)',
 'N111N': 'Dwellings (net)',
 'N112N': 'Other buildings and structures (net)',
 'N1121N': 'Buildings other than dwellings (net)',
 'N1122N': 'Other structures (net)',
 'N11MN': 'Machinery and equipment and weapons systems (net)',
 'N1131N': 'Transport equipment (net)',
 'N1132N': 'ICT equipment (net)',
 'N11321N': 'Computer hardware (net)',
 'N11322N': 'Telecommunications equipment (net)',
 'N11ON': 'Other machinery and equipment and weapons systems (net)',
 'N115N': 'Cultivated biological resources (net)',
 'N117N': 'Intellectual property products (net)',
 'N1171N': 'Research and development (net)',
 'N1172N': 'Mineral exploration and evaluation (net)',
 'N1173N': 'Computer software and databases (net)',
 'N1174N': 'Entertainment, literary or artistic originals (net)',
 'N1179N': 'Other intellectual property products (net)',
 'N12N': 'Inventories  (net)',
 'N13N': 'Valuables (net)',
 'N1MN': 'Inventories and acquisitions less disposals of valuables (net)',
 'N2N': 'Non-produced non-financial assets (net)',
 'N21N': 'Natural resources (net)',
 'N211N': 'Land (net)',
 'N212N': 'Mineral and energy reserves (net)',
 'N21ON': 'Non-cultivated biological resources and water resources (net)',
 'N215N': 'Other natural resources (net)',
 'N22N': 'Contracts, leases and licences (net)',
 'N23N': 'Purchases less sales of goodwill and marketing assets (net)',
 'N1G': 'Produced non-financial assets (gross)',
 'N1OG': 'Fixed assets and inventories (gross)',
 'N11G': 'Total fixed assets (gross)',
 'N11KG': 'Total Construction (gross)',
 'N111G': 'Dwellings (gross)',
 'N112G': 'Other buildings and structures (gross)',
 'N1121G': 'Buildings other than dwellings (gross)',
 'N1122G': 'Other structures (gross)',
 'N11MG': 'Machinery and equipment and weapons systems (gross)',
 'N1131G': 'Transport equipment (gross)',
 'N1132G': 'ICT equipment (gross)',
 'N11321G': 'Computer hardware (gross)',
 'N11322G': 'Telecommunications equipment (gross)',
 'N11OG': 'Other machinery and equipment and weapons systems (gross)',
 'N115G': 'Cultivated biological resources (gross)',
 'N117G': 'Intellectual property products (gross)',
 'N1171G': 'Research and development (gross)',
 'N1172G': 'Mineral exploration and evaluation (gross)',
 'N1173G': 'Computer software and databases (gross)',
 'N1174G': 'Entertainment, literary or artistic originals (gross)',
 'N1179G': 'Other intellectual property products (gross)',
 'N12G': 'Inventories  (gross)',
 'N13G': 'Valuables (gross)',
 'N1MG': 'Inventories and acquisitions less disposals of valuables (gross)',
 'N2G': 'Non-produced non-financial assets (gross)',
 'N21G': 'Natural resources (gross)',
 'N211G': 'Land (gross)',
 'N212G': 'Mineral and energy reserves (gross)',
 'N21OG': 'Non-cultivated biological resources and water resources (gross)',
 'N215G': 'Other natural resources (gross)',
 'N22G': 'Contracts, leases and licences (gross)',
 'N23G': 'Purchases less sales of goodwill and marketing assets (gross)'}

In [8]:
#print the units in the database
assets=[]
for u in df.asset10.unique():
    if u in dic_asset:
        assets.append(dic_asset[u])
#select the unit that we want
assets

['Dwellings (gross)',
 'Dwellings (net)',
 'Other buildings and structures (gross)',
 'Other buildings and structures (net)',
 'Transport equipment (gross)',
 'Transport equipment (net)',
 'Computer hardware (gross)',
 'Computer hardware (net)',
 'Telecommunications equipment (gross)',
 'Telecommunications equipment (net)',
 'ICT equipment (gross)',
 'ICT equipment (net)',
 'Cultivated biological resources (gross)',
 'Cultivated biological resources (net)',
 'Research and development (gross)',
 'Research and development (net)',
 'Computer software and databases (gross)',
 'Computer software and databases (net)',
 'Intellectual property products (gross)',
 'Intellectual property products (net)',
 'Total fixed assets (gross)',
 'Total Construction (gross)',
 'Total Construction (net)',
 'Machinery and equipment and weapons systems (gross)',
 'Machinery and equipment and weapons systems (net)',
 'Total fixed assets (net)',
 'Other machinery and equipment and weapons systems (gross)',
 'Other machinery and equipment and weapons systems (net)']

In [9]:
df.geo.unique()

array(['AT', 'BE', 'BG', 'CY', 'CZ', 'DE', 'EE', 'EL', 'ES', 'FI', 'FR',
       'IE', 'IT', 'LT', 'LU', 'LV', 'MT', 'PT', 'SI', 'SK', 'HR', 'NO',
       'DK', 'HU', 'NL', 'PL', 'RO', 'SE', 'ME', 'UK'], dtype=object)

In [10]:
df.unit.unique()

array(['CLV15_MEUR', 'CLV15_MNAC', 'CRC_MEUR', 'CRC_MNAC', 'PYR_MEUR',
       'PYR_MNAC'], dtype=object)

CLV15_MEUR 	Chain linked volumes (2015), million euro
	CLV15_MNAC 	Chain linked volumes (2015), million units of n...
	CRC_MEUR 	Current replacement costs, million euro
	CRC_MNAC 	Current replacement costs, million units of nat...
	PYR_MEUR 	Previous year replacement costs, million euro
	PYR_MNAC 	Previous year replacement costs, million units ...

In [11]:
unit=["CLV15_MEUR"]

In [12]:
cols = ['AT', 'BE', 'BG', 'CY', 'CZ', 'DE', 'DK', 'EE', 'EL', 'ES', 'FI','FR', 'HR', 'HU', 'IE', 'IT', 'LT','LU', 'LV', 'MT','NL', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK']
countries= set(cols)

In [13]:
df.nace_r2.unique()

array(['A', 'A01', 'A02', 'A03', 'B', 'B-E', 'C', 'C10-C12', 'C13-C15',
       'C16', 'C16-C18', 'C17', 'C18', 'C19', 'C20', 'C21', 'C22',
       'C22_C23', 'C23', 'C24', 'C24_C25', 'C25', 'C26', 'C27', 'C28',
       'C29', 'C29_C30', 'C30', 'C31-C33', 'C31_C32', 'C33', 'D', 'E',
       'E36', 'E37-E39', 'F', 'G', 'G-I', 'G45', 'G46', 'G47', 'H', 'H49',
       'H50', 'H51', 'H52', 'H53', 'I', 'J', 'J58', 'J58-J60', 'J59_J60',
       'J61', 'J62_J63', 'K', 'K64', 'K65', 'K66', 'L', 'L68A', 'M',
       'M69-M71', 'M69_M70', 'M71', 'M72', 'M73', 'M73-M75', 'M74_M75',
       'M_N', 'N', 'N77', 'N78', 'N79', 'N80-N82', 'O', 'O-Q', 'P', 'Q',
       'Q86', 'Q87_Q88', 'R', 'R-U', 'R90-R92', 'R93', 'S', 'S94', 'S95',
       'S96', 'T', 'TOTAL', 'U'], dtype=object)

In [14]:
weights_target = pd.read_excel("ecosystemweights.xlsx")
weights_target.NACE_R2.unique()

array(['A', 'C10-C12', 'C13-C15', 'C16', 'C17', 'C18', 'C19', 'C20',
       'C21', 'C22', 'C23', 'C24', 'C25', 'C26', 'C27', 'C28', 'C29',
       'C30', 'C31', 'C32', 'C33', 'D', 'E36', 'E37-E39', 'F', 'G45',
       'G46', 'G47', 'H49', 'H50', 'H51', 'H52', 'H53', 'I', 'J58',
       'J59_J60', 'J61', 'J62_J63', 'L', 'M69_M70', 'M71', 'M72', 'M73',
       'M74_M75', 'N77', 'N78', 'N79', 'N80', 'N81', 'N82', 'P', 'Q86',
       'Q87_Q88', 'R90-R92', 'R93', 'S94', 'S95', 'S96', 'T'],
      dtype=object)

In [15]:
nace_equal=set(weights_target.NACE_R2.unique())&set(df.nace_r2.unique())
nace_equal

{'A',
 'C10-C12',
 'C13-C15',
 'C16',
 'C17',
 'C18',
 'C19',
 'C20',
 'C21',
 'C22',
 'C23',
 'C24',
 'C25',
 'C26',
 'C27',
 'C28',
 'C29',
 'C30',
 'C33',
 'D',
 'E36',
 'E37-E39',
 'F',
 'G45',
 'G46',
 'G47',
 'H49',
 'H50',
 'H51',
 'H52',
 'H53',
 'I',
 'J58',
 'J59_J60',
 'J61',
 'J62_J63',
 'L',
 'M69_M70',
 'M71',
 'M72',
 'M73',
 'M74_M75',
 'N77',
 'N78',
 'N79',
 'P',
 'Q86',
 'Q87_Q88',
 'R90-R92',
 'R93',
 'S94',
 'S95',
 'S96',
 'T'}

In [16]:
nace_dif=set(weights_target.NACE_R2.unique())-set(df.nace_r2.unique())
nace_dif

{'C31', 'C32', 'N80', 'N81', 'N82'}

In [17]:
#ratios to divide N80_82 and 31_32. Value Added from SBS
ratios_values = pd.read_excel("ratioCN-Value added at factor cost - million euro.xlsx")
ratios_values.set_index('nace_r2', inplace=True)#nace como índice
ratios_values

,Value added at factor cost - million euro2011,Value added at factor cost - million euro2012,Value added at factor cost - million euro2013,Value added at factor cost - million euro2014,Value added at factor cost - million euro2015,Value added at factor cost - million euro2016,Value added at factor cost - million euro2017,Value added at factor cost - million euro2018,Value added at factor cost - million euro2019
nace_r2,,,,,,,,,
C31,0.398512,0.403322,0.400551,0.398158,0.400751,0.409175,0.388565,0.382716,0.390244
C32,0.601488,0.596678,0.599449,0.601842,0.599249,0.590825,0.611435,0.617284,0.609756
N80,0.165778,0.162820,0.158483,0.152327,0.157963,0.160093,0.155610,0.145835,0.145557
N81,0.462572,0.459438,0.466741,0.463845,0.467105,0.467350,0.469511,0.477816,0.490550
N82,0.371650,0.377742,0.374777,0.383828,0.374932,0.372558,0.374879,0.376349,0.363893

In [18]:
nace_include=['C31_C32','N80-N82']
nace_sel=set(nace_equal)|set(nace_include)
nace_sel

{'A',
 'C10-C12',
 'C13-C15',
 'C16',
 'C17',
 'C18',
 'C19',
 'C20',
 'C21',
 'C22',
 'C23',
 'C24',
 'C25',
 'C26',
 'C27',
 'C28',
 'C29',
 'C30',
 'C31_C32',
 'C33',
 'D',
 'E36',
 'E37-E39',
 'F',
 'G45',
 'G46',
 'G47',
 'H49',
 'H50',
 'H51',
 'H52',
 'H53',
 'I',
 'J58',
 'J59_J60',
 'J61',
 'J62_J63',
 'L',
 'M69_M70',
 'M71',
 'M72',
 'M73',
 'M74_M75',
 'N77',
 'N78',
 'N79',
 'N80-N82',
 'P',
 'Q86',
 'Q87_Q88',
 'R90-R92',
 'R93',
 'S94',
 'S95',
 'S96',
 'T'}

In [19]:
#we select the rows that have the right unit, nace codes, items and countries
df_selection=df[df.asset10.isin(asset)&df.nace_r2.isin(nace_sel)&df.geo.isin(countries)&df.unit.isin(unit)]
df_selection

,unit,nace_r2,asset10,geo,2021,2019,2018,2017,2016,2015,2014,2013,2012,2011
0,CLV15_MEUR,A,N111G,AT,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1,CLV15_MEUR,A,N111G,BE,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2,CLV15_MEUR,A,N111G,BG,NaN,2234.0,2027.9,1839.3,1668.3,1514.1,1369.6,1239.8,1122.7,1016.0
3,CLV15_MEUR,A,N111G,CY,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
4,CLV15_MEUR,A,N111G,CZ,NaN,318.6,302.7,292.7,283.9,313.1,294.8,314.4,305.5,318.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34179,CLV15_MEUR,T,N11ON,LV,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
34180,CLV15_MEUR,T,N11ON,MT,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
34181,CLV15_MEUR,T,N11ON,NL,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
34183,CLV15_MEUR,T,N11ON,SI,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
34184,CLV15_MEUR,T,N11ON,SK,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN

In [20]:
import numpy as np


for z in range(0,len(asset)):
    #create a dataframe for the results
    results_compiled = pd.DataFrame()
    #print the variable that we are going to calculate
    print(asset[z], assets[z])
    var=[asset[z]]#to pass it to a list to be able to apply isin
    #get the name of the variable and name it as the variable of interest
    variable_of_interest=asset[z]
    df_selection=df[df.asset10.isin(var)&df.nace_r2.isin(nace_sel)&df.geo.isin(countries)&df.unit.isin(unit)]
    if set(df_selection.geo.unique())==set(countries):
        print("No missing countries in the data") 
        #loop to calculate values for years
        for j in range (2011,2020):
            year=j
            #we transpose the values for the year selected
            for i in range (year,year+1):
                df_target = pd.pivot_table(df_selection, values=i, index=['nace_r2'],columns=["geo"], aggfunc=np.sum, fill_value=0)#reorde
            df_target['sum'] = df_target[cols].sum(axis=1)#sums the columns of the countries to "sum" 
            moddf_target = df_target.rename({'sum': 'EU27_2020'}, axis=1)  # rename column
            #add rows C31,... and assign value with the ratio multiplying by the value of position C31_32
            year_ratio=j-2011 
            moddf_target.loc['C31'] = ratios_values.iloc[0][year_ratio]*moddf_target.loc['C31_C32','EU27_2020']
            moddf_target.loc['C32'] = ratios_values.iloc[1][year_ratio]*moddf_target.loc['C31_C32','EU27_2020']
            moddf_target.loc['N80'] = ratios_values.iloc[2][year_ratio]*moddf_target.loc['N80-N82','EU27_2020']
            moddf_target.loc['N81'] = ratios_values.iloc[3][year_ratio]*moddf_target.loc['N80-N82','EU27_2020']
            moddf_target.loc['N82'] = ratios_values.iloc[4][year_ratio]*moddf_target.loc['N80-N82','EU27_2020']
            #we eliminate rows C31_C32
            moddf_target = moddf_target.drop(['C31_C32', 'N80-N82'])
            pd.set_option('display.float_format', lambda x: '%.4f' % x)
            #cargamos los pesos en el dataframe weight  
            weights_target = pd.read_excel("ecosystemweights.xlsx")
            weights_target.set_index('NACE_R2', inplace=True)#nace como índice
            column_name=str(variable_of_interest)+str(year)
            weights_target[variable_of_interest]=weights_target.index.map(moddf_target['EU27_2020'])#busca en df_target el nace y copia el valor de EU27_2020 en la fila del nace the weights_target
            #creamos la matriz de resultados
            results=weights_target
            for i in range(0,14):
                results.iloc[:, i]=weights_target.iloc[:, i]*weights_target[variable_of_interest]#we multiply the total value added by the weight for each nace
            results.loc['total'] = results.select_dtypes(pd.np.number).sum() #we add the values of each colum in a row call total
            results_compiled[column_name]=results.loc['total']
        results_compiled = results_compiled.drop(variable_of_interest)
        #results_compiled.loc['total'] = results_compiled.select_dtypes(pd.np.number).sum()
        display(results_compiled) 
        #save to file
        filename = "%s.xlsx" % variable_of_interest
        results_compiled.to_excel(filename)
    else:
        print("Missing countries in the data:", set(countries)-set(df_selection.geo.unique()))

N111G Dwellings (gross)
Missing countries in the data: {'SE', 'HR'}
N111N Dwellings (net)
No missing countries in the data

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:42: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

,N111N2011,N111N2012,N111N2013,N111N2014,N111N2015,N111N2016,N111N2017,N111N2018,N111N2019
Aerospace & Defence,649.2274,575.2439,546.8973,553.1354,626.9817,735.8289,868.0009,1018.2412,1291.7714
Agri-food,29124.5994,18367.6233,11889.9253,7993.1321,5698.9387,4327.4000,3554.8182,3146.1900,2971.5500
Construction,241362.7016,243081.1271,248032.8428,255272.4561,262767.4229,271784.8901,281475.1987,294311.4073,309826.6542
Cultural and Creative Industries,2462.8550,1947.6349,1647.8961,1464.9644,1373.8983,1333.5128,1378.9884,1408.7868,1469.0640
Digital,199.4384,202.5127,204.6435,205.8746,211.2726,210.9939,214.6026,220.1429,226.3444
Electronics,61.8285,62.4166,63.2409,63.9805,65.7121,67.2720,67.3580,69.6964,72.8821
Energy - Renewables,381.8925,378.2072,373.0024,367.4336,374.6248,379.0374,380.1299,383.6104,387.3604
Energy Intensive Industries,675.5152,741.8236,819.2086,912.5464,1047.9880,1215.5615,1435.2474,1715.8876,2101.3764
Health,4277.3709,4236.5945,4285.5023,4271.6769,4341.6646,4442.4177,4493.1439,4425.6563,4405.0382
Mobility - Transport - Automotive,1355.3636,1118.2027,962.5719,861.3430,815.4991,791.4935,797.3653,818.1235,853.1791
"Proximity, Social Economy and Civil Security",1455165.4601,1462626.6275,1472631.7382,1480797.2520,1492067.0339,1504672.9671,1516336.2210,1530314.8925,1544902.6921
Retail,32089.2866,20737.4752,13721.3528,9376.7775,6665.8648,4967.7243,3922.8896,3249.6219,2842.8268
Textile,811.4969,877.4533,947.8516,1026.4626,1111.7201,1202.3297,1304.2717,1418.0665,1559.0303
Tourism,34662.3606,21428.3469,13608.6119,9085.6045,6532.6421,5374.4961,4859.9627,4822.1137,5175.2562

N112G Other buildings and structures (gross)
Missing countries in the data: {'SE'}
N112N Other buildings and structures (net)
No missing countries in the data

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:42: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

,N112N2011,N112N2012,N112N2013,N112N2014,N112N2015,N112N2016,N112N2017,N112N2018,N112N2019
Aerospace & Defence,54257.6245,60818.4359,60877.2070,61102.7641,62035.0351,62755.0492,63390.8240,63738.2122,57273.7470
Agri-food,628358.5647,626245.0564,622313.9676,618907.8568,615495.8029,611136.5611,607678.9510,604923.5277,586200.3348
Construction,438416.9281,440207.0308,434511.2949,432670.8771,430546.9191,431466.9860,430988.6669,431551.4451,434583.8402
Cultural and Creative Industries,108441.0277,111869.5688,111887.1654,111630.9057,111798.5995,111759.5578,111411.9027,111450.1200,111454.7546
Digital,165356.7217,166074.4252,167078.9179,168457.4753,169785.0967,171743.4227,174170.8189,176762.7185,138997.4679
Electronics,21885.7867,21850.1736,21669.4805,21723.1640,21875.7583,22446.2644,22611.1662,22610.4365,15993.6288
Energy - Renewables,237022.3695,239410.1159,240151.2884,242726.6015,244829.1602,246405.8155,245848.5781,246942.3107,248285.9586
Energy Intensive Industries,137017.0290,147383.8557,147123.6559,145769.7291,145623.5354,147091.2547,148804.0845,150773.4634,122406.7327
Health,413299.3860,421401.3416,426782.8324,429898.8232,433773.3466,436166.0850,437122.8501,437940.1991,375019.7191
Mobility - Transport - Automotive,142787.6487,164078.7596,165246.0810,165915.5617,168842.2314,170794.9417,172931.9696,174459.1062,170813.2523
"Proximity, Social Economy and Civil Security",333301.4748,340659.8885,345768.8602,349722.3623,354644.1895,358721.3475,361938.6954,365379.3571,360820.7009
Retail,122116.5118,144449.0155,144965.9895,145752.1667,146110.1001,148078.8165,149072.5701,150346.2557,150940.6014
Textile,23365.6432,23186.5717,22797.5322,22469.1765,22150.8478,22027.1072,21791.5850,21659.1685,14994.5888
Tourism,394065.2384,404276.5789,405644.9524,406327.8975,411529.1505,415671.5771,421042.5391,426640.9653,431287.3358

N1131G Transport equipment (gross)
No missing countries in the data

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:42: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

,N1131G2011,N1131G2012,N1131G2013,N1131G2014,N1131G2015,N1131G2016,N1131G2017,N1131G2018,N1131G2019
Aerospace & Defence,5969.9835,6524.3298,6477.7330,6481.8008,6546.9295,6691.8885,6853.1007,6937.1947,6623.3310
Agri-food,74903.5611,74743.8196,74891.3456,74980.3129,75361.7309,74974.3631,75058.8398,75677.6942,75771.0885
Construction,108610.9628,107775.1728,107091.2534,106439.0093,104759.9162,105376.1190,106382.2329,108482.2257,109914.2313
Cultural and Creative Industries,6589.7482,6592.3591,6421.5905,6279.7951,6173.5197,6127.4756,6115.5079,6113.4453,6066.7476
Digital,15105.6252,15683.6214,16553.6196,18247.8675,19813.3561,20948.3935,22214.5487,22995.0352,19534.4121
Electronics,2696.2085,2619.4064,2513.2635,2423.0436,2341.8192,2307.4850,2324.3544,2340.8855,1978.2110
Energy - Renewables,8317.3759,8517.9562,8659.1638,8939.9765,9043.3036,9197.3989,9664.5816,10187.6952,10594.5862
Energy Intensive Industries,11277.6354,11444.2295,11518.6954,11564.0721,11537.4569,11585.1212,11696.9955,12062.1382,11762.9441
Health,22219.2443,22718.1413,22989.3499,23193.6803,23178.2146,23188.6627,23467.4115,23584.3673,21632.0211
Mobility - Transport - Automotive,106123.5266,115617.2537,116937.1675,118724.0677,120435.0056,121119.3275,123971.3910,127142.8621,128054.5685
"Proximity, Social Economy and Civil Security",13458.6574,13869.7655,14081.7841,14213.7833,14376.2288,14654.2486,14994.6307,15358.3740,14900.9160
Retail,27365.9528,28529.9704,28165.1027,28190.5168,27807.2410,27637.1897,27354.9966,27119.4243,26659.6768
Textile,3501.0994,3323.3239,3168.5432,3029.7844,2890.6471,2808.5701,2766.9616,2704.6403,1483.1479
Tourism,75477.4024,86462.6686,86296.1136,86367.7865,85682.0288,85618.7279,87374.0807,88561.4573,89302.4391

N1131N Transport equipment (net)
No missing countries in the data

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:42: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

,N1131N2011,N1131N2012,N1131N2013,N1131N2014,N1131N2015,N1131N2016,N1131N2017,N1131N2018,N1131N2019
Aerospace & Defence,3849.5149,4033.7763,4035.2454,4068.7751,4178.6736,4352.5638,4596.4295,4692.2527,4690.0943
Agri-food,38834.0028,38515.3428,38294.2298,38207.9955,38586.7554,38550.1496,39383.7616,40690.0000,41965.7959
Construction,65273.8427,64033.8454,63324.7831,63145.5278,62168.8370,64082.4715,66587.2444,69886.8729,72109.4513
Cultural and Creative Industries,4112.2536,4073.4764,3989.2675,3931.8138,3943.4672,4000.5384,4100.2394,4221.1989,4300.0975
Digital,9525.7615,9988.0363,10665.7821,12138.8715,13427.6380,14155.5095,15091.0908,15499.1693,12714.6131
Electronics,1546.7463,1493.0523,1421.0634,1373.2412,1348.5853,1367.3810,1431.3163,1479.5918,1343.3487
Energy - Renewables,4654.6667,4696.3309,4694.6246,4843.4297,4829.9783,4936.6259,5317.8058,5732.0155,6042.6240
Energy Intensive Industries,6708.0684,6683.1996,6600.6654,6622.1941,6606.0933,6676.6670,6874.9646,7287.3859,7252.5877
Health,13204.4328,13403.9657,13453.4748,13549.8751,13567.7074,13693.3482,14089.6036,14363.1447,13598.8549
Mobility - Transport - Automotive,68900.6029,70527.8895,68333.3805,67939.2519,67431.3152,67792.1222,68707.2613,70302.8115,70155.3907
"Proximity, Social Economy and Civil Security",8315.7982,8497.7328,8568.7032,8659.7310,8844.9713,9185.8987,9658.2999,10084.3073,10025.9136
Retail,18145.9106,18546.2618,18218.1048,18327.3697,18330.6445,18646.4782,19000.4028,19358.6491,19398.4920
Textile,1795.1967,1654.8197,1544.2038,1472.1195,1416.1439,1421.4215,1465.4741,1482.7568,921.2642
Tourism,48327.7472,51723.9315,51010.4449,50428.8388,49608.8940,50074.3827,51541.4292,52364.3536,54218.8181

N11321G Computer hardware (gross)
Missing countries in the data: {'HR', 'PT', 'DK', 'RO', 'SE', 'BG', 'ES', 'PL', 'IE', 'HU', 'DE'}
N11321N Computer hardware (net)
Missing countries in the data: {'HR', 'PT', 'DK', 'RO', 'BG', 'ES', 'PL', 'IE', 'HU', 'DE'}
N11322G Telecommunications equipment (gross)
Missing countries in the data: {'HR', 'CY', 'PT', 'DK', 'RO', 'SE', 'BG', 'ES', 'PL', 'IE', 'HU', 'DE'}
N11322N Telecommunications equipment (net)
Missing countries in the data: {'HR', 'CY', 'PT', 'DK', 'RO', 'BG', 'ES', 'PL', 'IE', 'HU', 'DE'}
N1132G ICT equipment (gross)
Missing countries in the data: {'HR', 'CY', 'PT', 'DK', 'RO', 'SE', 'BG', 'ES', 'PL', 'IE', 'HU', 'DE'}
N1132N ICT equipment (net)
Missing countries in the data: {'HR', 'CY', 'PT', 'DK', 'RO', 'BG', 'ES', 'PL', 'IE', 'HU', 'DE'}
N115G Cultivated biological resources (gross)
Missing countries in the data: {'SE'}
N115N Cultivated biological resources (net)
No missing countries in the data

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:42: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

,N115N2011,N115N2012,N115N2013,N115N2014,N115N2015,N115N2016,N115N2017,N115N2018,N115N2019
Aerospace & Defence,248.0945,243.0468,242.3676,244.4027,242.0575,239.6543,230.6391,223.8674,230.1895
Agri-food,84042.1829,85282.0773,86226.0525,86399.5809,87091.3097,86066.4784,87657.9879,87739.9515,89009.0698
Construction,403.5017,388.2799,390.7037,403.0589,402.3105,395.4929,381.9818,370.8777,389.4900
Cultural and Creative Industries,152.7681,147.3020,147.6983,145.3147,145.9910,142.4896,137.1856,137.3949,147.3984
Digital,270.5321,267.2323,268.6059,282.4805,282.1693,275.8237,270.2149,258.3902,307.8969
Electronics,136.7141,137.1124,138.9671,141.1518,142.6517,142.2630,142.5133,142.0762,144.0651
Energy - Renewables,593.8259,578.3262,565.2508,562.5803,549.3187,531.5937,502.3647,477.1334,473.7558
Energy Intensive Industries,1155.7158,1125.8541,1114.6359,1123.1881,1106.4640,1091.0379,1067.7340,1031.0065,1047.7468
Health,410.8713,400.9072,392.8606,391.4683,382.6701,370.5686,355.2413,340.7603,343.5460
Mobility - Transport - Automotive,1351.0970,1302.7187,1275.7956,1276.6739,1260.6545,1236.2376,1177.8571,1141.9381,1183.6650
"Proximity, Social Economy and Civil Security",137.1935,135.8493,135.8495,134.8281,133.8068,132.0164,132.4873,161.9785,184.5200
Retail,832.2507,807.1626,797.0628,797.9008,824.9573,815.7169,808.9341,789.9754,804.8540
Textile,60.2186,58.2878,56.6958,56.5067,55.7274,54.0995,51.7281,49.5488,53.3287
Tourism,1103.6440,1093.6262,1091.0059,1091.3743,1073.3997,1073.9877,1062.2277,1062.3128,1080.6414

N1171G Research and development (gross)
Missing countries in the data: {'HR', 'CY', 'PT', 'DK', 'SE', 'ES', 'PL', 'IE'}
N1171N Research and development (net)
Missing countries in the data: {'HR', 'CY', 'PT', 'DK', 'ES', 'PL', 'IE'}
N1173G Computer software and databases (gross)
Missing countries in the data: {'HR', 'CY', 'PT', 'DK', 'SE', 'BG', 'ES', 'PL', 'IE', 'MT'}
N1173N Computer software and databases (net)
Missing countries in the data: {'HR', 'CY', 'PT', 'DK', 'BG', 'ES', 'PL', 'IE', 'MT'}
N117G Intellectual property products (gross)
Missing countries in the data: {'HR', 'CY', 'PT', 'SE', 'ES', 'IE', 'MT'}
N117N Intellectual property products (net)
Missing countries in the data: {'HR', 'CY', 'PT', 'ES', 'IE', 'MT'}
N11G Total fixed assets (gross)
Missing countries in the data: {'HR', 'CY', 'PT', 'SE', 'BG'}
N11KG Total Construction (gross)
Missing countries in the data: {'SE', 'BG', 'IE'}
N11KN Total Construction (net)
Missing countries in the data: {'IE', 'BG'}
N11MG Machinery and equipment and weapons systems (gross)
Missing countries in the data: {'SE'}
N11MN Machinery and equipment and weapons systems (net)
No missing countries in the data

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:42: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

,N11MN2011,N11MN2012,N11MN2013,N11MN2014,N11MN2015,N11MN2016,N11MN2017,N11MN2018,N11MN2019
Aerospace & Defence,34879.4991,35098.9458,35355.5207,35294.0518,35539.5566,35953.8933,36801.9034,37491.3829,29986.5936
Agri-food,366388.5104,368308.5571,369859.9447,371099.8153,371909.8795,371939.9834,376096.5806,385058.6697,350365.2139
Construction,222704.7104,220710.6206,217949.8506,216193.4322,213607.6223,215831.4336,221332.5313,228541.7795,231381.8127
Cultural and Creative Industries,28495.9741,29249.8175,29161.2306,28929.6391,28982.1335,28914.6953,29163.7982,29187.0595,29037.0744
Digital,107123.1987,107285.5675,109717.4313,113283.2001,117772.2193,121397.5296,124443.0117,127455.8055,105598.5389
Electronics,32068.4139,31479.1529,31378.5287,30757.2517,30416.6666,30308.6658,30922.8908,31531.5597,21647.8024
Energy - Renewables,102176.8383,105822.4294,109777.1987,113310.2583,114702.0758,115654.6943,116762.0447,117887.6702,115073.0022
Energy Intensive Industries,180299.6659,187140.2680,187850.2029,188677.5318,190315.9985,190600.4573,192437.4026,193955.1738,167635.1337
Health,122755.0582,124652.7834,126190.6501,127916.4112,129794.5725,131785.6825,135262.5295,137936.4294,110299.0111
Mobility - Transport - Automotive,131993.6941,134044.4063,134696.6462,136107.2481,138421.3305,144263.4546,148060.0385,152566.1366,147676.9373
"Proximity, Social Economy and Civil Security",50158.3945,51255.1041,51378.1078,51701.5427,52171.9624,53029.6546,54105.2343,55103.6690,53713.6046
Retail,72532.5480,79619.5516,79946.3633,80868.2456,81555.0919,83032.6180,85587.6034,87748.3455,87954.6223
Textile,31134.0597,30144.7383,29284.6474,28661.6721,28202.2829,27611.1491,27674.7027,27947.1459,11236.4357
Tourism,154565.9933,153787.3424,153025.3379,152275.1347,151322.6089,154683.7179,156876.1369,158583.1776,160845.2843

N11N Total fixed assets (net)
Missing countries in the data: {'BG', 'HR', 'CY', 'PT'}
N11OG Other machinery and equipment and weapons systems (gross)
Missing countries in the data: {'HR', 'CY', 'PT', 'DK', 'RO', 'SE', 'BG', 'ES', 'PL', 'IE', 'HU'}
N11ON Other machinery and equipment and weapons systems (net)
Missing countries in the data: {'HR', 'CY', 'PT', 'DK', 'RO', 'BG', 'ES', 'PL', 'IE', 'HU'}