In [1]:
# pandas
import pandas as pd 
# pip install eurostat  #herramienta para importar datos de eurostat

In [2]:
import PySimpleGUI as sg
def selection(option):
    #sg.theme('DarkAmber')   # Add a touch of color
    #select the variable we want to calculate
    options = option

    # All the stuff inside your window.
    layout = [ 
            [sg.Text('Select one->'), sg.Listbox(options,select_mode=sg.LISTBOX_SELECT_MODE_SINGLE,size=(20,len(options)))],
            [sg.Button('Ok'), sg.Button('Cancel')]
        ]

    # Create the Window
    window = sg.Window('Make your choice', layout)

    # Event Loop to process "events" and get the "values" of the input
    while True:
        event, values = window.read()
        print( f"event={event}" )
        if event is None or event == 'Ok' or event == 'Cancel': # if user closes window or clicks cancel
            break
        
    # close  the window        
    window.close()

    if event == "Cancel":
        print( "You cancelled" )
    else:
        print('You entered ', values[0])
        sg.popup( f"You selected {values[0]}" )        
    return values

In [3]:
#change the number to select another database
database_sel= 'env_ac_ainah_r2' 
database_sel

'env_ac_ainah_r2'

In [4]:
#nama_10_a64 National accounts aggregates by industry (up to NACE A*64)
#NAMA_10_A64_P5 Gross capital formation by industry (up to NACE A*64)
#National accounts employment data by industry (up to NACE A*64)

import eurostat
df = eurostat.get_data_df(database_sel, flags=False)
df

,airpol,nace_r2,unit,geo\time,2020,2019,2018,2017,2016,2015,...,2004,2003,2002,2001,2000,1999,1998,1997,1996,1995
0,ACG,A,G_HAB,AT,NaN,14046.27,14168.32,14478.39,14455.49,14434.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ACG,A,G_HAB,BE,NaN,11574.89,12010.43,12212.35,12565.84,12627.93,...,15720.77,16706.26,17632.17,18158.37,18747.25,NaN,NaN,NaN,NaN,NaN
2,ACG,A,G_HAB,BG,NaN,6521.38,6251.92,5803.93,5732.92,5717.08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ACG,A,G_HAB,CH,NaN,11772.20,12067.02,12294.59,12444.77,12618.58,...,14273.97,14400.73,14709.49,15115.45,15214.75,NaN,NaN,NaN,NaN,NaN
4,ACG,A,G_HAB,CY,NaN,15785.66,19660.42,19610.08,19667.98,19107.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266771,SOX_SO2E,U,THS_T,SE,0.0,0.00,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266772,SOX_SO2E,U,THS_T,SI,NaN,0.00,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266773,SOX_SO2E,U,THS_T,SK,NaN,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0
266774,SOX_SO2E,U,THS_T,TR,NaN,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0
266775,SOX_SO2E,U,THS_T,UK,NaN,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0

In [5]:
df.columns

Index([  'airpol',  'nace_r2',     'unit', 'geo\time',       2020,       2019,
             2018,       2017,       2016,       2015,       2014,       2013,
             2012,       2011,       2010,       2009,       2008,       2007,
             2006,       2005,       2004,       2003,       2002,       2001,
             2000,       1999,       1998,       1997,       1996,       1995],
      dtype='object')

In [6]:
#eliminate columns for years previous to 2011
years =[]
year_start=1995
year_study=2011
for y in range(year_start,year_study): 
    years.append(y)
df=df.drop(years, axis=1)#quitamos todas las columnas de añosque no nos interesan
#rename geo time column to be easier to handle because of the name
df.rename(columns={"geo\\time": "geo"}, inplace=True)
#We can get the unique values of the different variables

In [7]:
dic_unit = eurostat.get_dic('unit') #dictionary for all the unit in eurostat
#print the units in the database
for u in df.unit.unique():
    if u in dic_unit:
        print (u + " -"+dic_unit[u])
#select the unit that we want
unit=selection(df.unit.unique())[0]

G_HAB -Grams per capita
KG_HAB -Kilograms per capita
T -Tonne
THS_T -Thousand tonnes
event=Ok
You entered  ['T']

In [8]:
dic_item = eurostat.get_dic('airpol') #dictionary for all the unit in eurostat
for item in df.airpol.unique():
    if item in dic_item:
        print (item + " -"+dic_item[item])
naitem=selection(df.airpol.unique())[0]

ACG -Acidifying gases (SOX in SO2 equivalent, NOX in SO2 equivalent, NH3 in SO2 equivalent)
CH4 -Methane
CH4_CO2E -Methane (CO2 equivalent)
CH4_NMVOCE -Methane (NMVOC equivalent)
CO -Carbon monoxide
CO2 -Carbon dioxide
CO2_BIO -Carbon dioxide from biomass used as a fuel
CO_NMVOCE -Carbon monoxide (NMVOC equivalent)
GHG -Greenhouse gases (CO2, N2O in CO2 equivalent, CH4 in CO2 equivalent, HFC in CO2 equivalent, PFC in CO2 equivalent, SF6 in CO2 equivalent, NF3 in CO2 equivalent)
HFC_CO2E -Hydrofluorocarbones (CO2 equivalent)
N2O -Nitrous oxide
N2O_CO2E -Nitrous oxide (CO2 equivalent)
NF3_SF6_CO2E -Nitrogen trifluoride and sulphur hexafluoride (CO2 equivalent)
NH3 -Ammonia
NH3_SO2E -Ammonia (SO2 equivalent)
NMVOC -Non-methane volatile organic compounds
NOX -Nitrogen oxides
NOX_NMVOCE -Nitrogen oxides (NMVOC equivalent)
NOX_SO2E -Nitrogen oxides (SO2 equivalent)
O3PR -Ozone precursors (NMVOC, NOX in NMVOC equivalent, CO in NMVOC equivalent, CH4 in NMVOC equivalent)
PFC_CO2E -Perfluorocarbones (CO2 equivalent)
PM10 -Particulates < 10µm
PM2_5 -Particulates < 2.5µm
SOX_SO2E -Sulphur oxides (SO2 equivalent)
event=Ok
You entered  ['GHG']

In [9]:
#determine the variable of interest based on the selection
for item in naitem:
    if item in dic_item:
        variable_of_interest=dic_item[item]
variable_of_interest

'Greenhouse gases (CO2, N2O in CO2 equivalent, CH4 in CO2 equivalent, HFC in CO2 equivalent, PFC in CO2 equivalent, SF6 in CO2 equivalent, NF3 in CO2 equivalent)'

In [10]:
df.nace_r2.unique()

array(['A', 'A01', 'A02', 'A03', 'B', 'C', 'C10-C12', 'C13-C15', 'C16',
       'C17', 'C18', 'C19', 'C20', 'C21', 'C22', 'C23', 'C24', 'C25',
       'C26', 'C27', 'C28', 'C29', 'C30', 'C31_C32', 'C33', 'D', 'E',
       'E36', 'E37-E39', 'F', 'G', 'G45', 'G46', 'G47', 'H', 'H49', 'H50',
       'H51', 'H52', 'H53', 'HH', 'HH_HEAT', 'HH_OTH', 'HH_TRA', 'I', 'J',
       'J58', 'J59_J60', 'J61', 'J62_J63', 'K', 'K64', 'K65', 'K66', 'L',
       'L68A', 'M', 'M69_M70', 'M71', 'M72', 'M73', 'M74_M75', 'N', 'N77',
       'N78', 'N79', 'N80-N82', 'O', 'P', 'Q', 'Q86', 'Q87_Q88', 'R',
       'R90-R92', 'R93', 'S', 'S94', 'S95', 'S96', 'T', 'TOTAL',
       'TOTAL_HH', 'U'], dtype=object)

In [11]:
nacedrop=['O','K66', 'J', 'H', 'C16-C18','A03', 'O-Q', 'E', 'C31-C33', 'M_N', 'J58-J60', 'R-U', 'G', 'K', 'TOTAL', 'L68A', 'A02', 'C22_C23', 'C29_C30',  'B-E', 'G-I', 'N', 'Q', 'R', 'C24_C25','C', 'M69-M71', 'M73-M75', 'U', 'S', 'B', 'M', 'A01', 'K65','K64']
countries_not_selected= ['UK', 'TR', 'AL','IS','LI','NO','CH','UK','ME','MK','AL','RS','TR','BA','EU28','EU15','EA','EA19','EA12']
#We can get the selected values we want from nace 
#naceall=df.nace_r2.unique()
#nace=set(naceall)-set(nacedrop)
#df[df.unit.isin(unit)&df.nace_r2.isin(nace)&df.na_item.isin(naitem)]
#or we can select those that are not in the list nacedrop by using ~df.nace_r2.isin(nacedrop) later

#we select the rows that have the right unit, nace codes, items and countries
df_selection=df[df.unit.isin(unit)&~df.nace_r2.isin(nacedrop)&df.airpol.isin(naitem)&~df.geo.isin(countries_not_selected)]
df_selection

,airpol,nace_r2,unit,geo,2020,2019,2018,2017,2016,2015,2014,2013,2012,2011
89656,GHG,A,T,AT,7.952156e+06,7.977510e+06,8.089180e+06,8.197550e+06,8.256551e+06,8.119674e+06,8.114213e+06,7.979740e+06,7.964552e+06,8.027715e+06
89657,GHG,A,T,BE,1.243494e+07,1.264914e+07,1.258234e+07,1.263173e+07,1.249085e+07,1.240415e+07,1.183429e+07,1.155815e+07,1.147165e+07,1.148033e+07
89658,GHG,A,T,BG,6.674684e+06,6.758869e+06,6.964650e+06,7.003300e+06,6.979935e+06,6.270766e+06,5.999345e+06,5.273209e+06,4.928959e+06,4.607972e+06
89660,GHG,A,T,CY,6.118093e+05,6.020983e+05,5.827283e+05,5.837196e+05,5.660959e+05,5.441686e+05,5.190505e+05,5.436425e+05,5.819932e+05,6.078354e+05
89661,GHG,A,T,CZ,9.187464e+06,9.560555e+06,9.837534e+06,1.003774e+07,1.012986e+07,1.006443e+07,9.525918e+06,9.443787e+06,9.471691e+06,9.590395e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99998,GHG,TOTAL_HH,T,PT,6.167973e+07,6.622845e+07,6.952562e+07,7.291216e+07,6.803495e+07,7.035971e+07,6.643172e+07,6.655397e+07,6.848985e+07,7.006993e+07
99999,GHG,TOTAL_HH,T,RO,1.111135e+08,1.166047e+08,1.208008e+08,1.196280e+08,1.158569e+08,1.181985e+08,1.168393e+08,1.165151e+08,1.251152e+08,1.275373e+08
100000,GHG,TOTAL_HH,T,SE,4.972125e+07,5.533703e+07,5.691377e+07,5.827354e+07,6.001401e+07,6.013037e+07,5.836973e+07,5.951501e+07,6.064816e+07,6.371906e+07
100001,GHG,TOTAL_HH,T,SI,1.795011e+07,1.874589e+07,1.905185e+07,1.920779e+07,1.875908e+07,1.772804e+07,1.726453e+07,1.884879e+07,1.954179e+07,2.030172e+07
100002,GHG,TOTAL_HH,T,SK,3.757545e+07,4.004921e+07,4.226640e+07,4.232292e+07,4.120982e+07,4.081099e+07,3.994578e+07,4.194053e+07,4.238981e+07,4.465748e+07

In [12]:
#ratios to divide N80_82 and 31_32. Value Added from SBS
ratios_values = pd.read_excel("ratioCN-Value added at factor cost - million euro.xlsx")
ratios_values.set_index('nace_r2', inplace=True)#nace como índice
ratios_values

,Value added at factor cost - million euro2011,Value added at factor cost - million euro2012,Value added at factor cost - million euro2013,Value added at factor cost - million euro2014,Value added at factor cost - million euro2015,Value added at factor cost - million euro2016,Value added at factor cost - million euro2017,Value added at factor cost - million euro2018,Value added at factor cost - million euro2019
nace_r2,,,,,,,,,
C31,0.398512,0.403322,0.400551,0.398158,0.400751,0.409175,0.388565,0.382716,0.390244
C32,0.601488,0.596678,0.599449,0.601842,0.599249,0.590825,0.611435,0.617284,0.609756
N80,0.165778,0.162820,0.158483,0.152327,0.157963,0.160093,0.155610,0.145835,0.145557
N81,0.462572,0.459438,0.466741,0.463845,0.467105,0.467350,0.469511,0.477816,0.490550
N82,0.371650,0.377742,0.374777,0.383828,0.374932,0.372558,0.374879,0.376349,0.363893

In [13]:
weights_target = pd.read_excel("ecosystemweights.xlsx")
weights_target

,NACE_R2,Aerospace & Defence,Agri-food,Construction,Cultural and Creative Industries,Digital,Electronics,Energy - Renewables,Energy Intensive Industries,Health,Mobility - Transport - Automotive,"Proximity, Social Economy and Civil Security",Retail,Textile,Tourism
0,A,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,C10-C12,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,C13-C15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
3,C16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,C17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,C18,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,C19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,C20,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,C21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,C22,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,C23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,C24,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,C25,0.097362,0.066168,0.305189,0.008982,0.020901,0.019600,0.015553,0.036324,0.051639,0.235501,0.023466,0.044200,0.008535,0.036845
13,C26,0.440000,0.000000,0.000000,0.000000,0.222517,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,C27,0.230000,0.000000,0.000000,0.000000,0.000000,0.000000,0.378114,0.000000,0.000000,0.025089,0.000000,0.000000,0.000000,0.000000
15,C28,0.067894,0.078244,0.198393,0.012618,0.030525,0.122558,0.015984,0.040056,0.056225,0.277642,0.029954,0.057346,0.009986,0.050067
16,C29,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
17,C30,0.681044,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.318958,0.000000,0.000000,0.000000,0.000000
18,C31,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,C32,0.000000,0.000000,0.000000,0.079000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,C33,0.166456,0.118497,0.155381,0.013205,0.032879,0.015305,0.016405,0.047373,0.068633,0.165263,0.035659,0.064677,0.009670,0.071660
21,D,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.290000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,E36,0.017444,0.121809,0.102483,0.024670,0.022172,0.006887,0.011280,0.040057,0.110972,0.058200,0.076530,0.074141,0.012856,0.104587
23,E37-E39,0.027442,0.094801,0.136681,0.018941,0.027805,0.010187,0.014313,0.086234,0.085284,0.098157,0.053702,0.077560,0.014370,0.071190
24,F,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,G45,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
26,G46,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
27,G47,0.000000,0.000000,0.000000,0.012000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.155000,1.000000,0.000000,0.000000
28,H49,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.517742,0.000000,0.000000,0.000000,0.445221
29,H50,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.777240,0.000000,0.000000,0.000000,0.222225
30,H51,0.092866,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.907134
31,H52,0.178000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.393612,0.000000,0.000000,0.000000,0.000000
32,H53,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
33,I,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.140000,0.000000,0.000000,1.000000
34,J58,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35,J59_J60,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
36,J61,0.069000,0.000000,0.000000,0.000000,0.972721,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37,J62_J63,0.000000,0.000000,0.000000,0.004000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
38,L,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.083600,0.000000,0.000000,0.000000
39,M69_M70,0.024984,0.077210,0.115127,0.027735,0.051335,0.011667,0.009650,0.049054,0.087623,0.086191,0.057233,0.134521,0.011523,0.067615
40,M71,0.033689,0.060163,1.256805,0.173047,0.044230,0.014561,0.011725,0.036812,0.076141,0.092899,0.044152,0.080038,0.011156,0.054884
41,M72,0.056517,0.072081,0.104068,0.027198,0.069032,0.050716,0.008286,0.030642,0.142165,0.129971,0.046536,0.081408,0.011505,0.048453
42,M73,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
43,M74_M75,0.000000,0.000000,0.000000,0.640000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
44,N77,0.027148,0.082093,0.129191,0.029051,0.051669,0.013045,0.008469,0.031288,0.099961,0.085503,0.061228,0.126924,0.009894,0.082765
45,N78,0.027148,0.082093,0.129191,0.028451,0.051669,0.013045,0.008469,0.031288,0.099961,0.085503,0.061228,0.126924,0.009894,0.082765
46,N79,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
47,N80,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
48,N81,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.280000,0.000000,0.000000,0.000000
49,N82,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.110000,0.000000,0.000000,1.000000
50,P,0.000000,0.000000,0.000000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
51,Q86,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
52,Q87_Q88,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000
53,R90-R92,0.000000,0.000000,0.000000,0.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.660000
54,R93,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
55,S94,0.000000,0.000000,0.000000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
56,S95,0.000000,0.000000,0.000000,0.260000,0.480000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
57,S96,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
58,T,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000

In [14]:
weights_target.NACE_R2.unique()

array(['A', 'C10-C12', 'C13-C15', 'C16', 'C17', 'C18', 'C19', 'C20',
       'C21', 'C22', 'C23', 'C24', 'C25', 'C26', 'C27', 'C28', 'C29',
       'C30', 'C31', 'C32', 'C33', 'D', 'E36', 'E37-E39', 'F', 'G45',
       'G46', 'G47', 'H49', 'H50', 'H51', 'H52', 'H53', 'I', 'J58',
       'J59_J60', 'J61', 'J62_J63', 'L', 'M69_M70', 'M71', 'M72', 'M73',
       'M74_M75', 'N77', 'N78', 'N79', 'N80', 'N81', 'N82', 'P', 'Q86',
       'Q87_Q88', 'R90-R92', 'R93', 'S94', 'S95', 'S96', 'T'],
      dtype=object)

In [15]:
# columns of countries to be eliminated
cols = ['AT', 'BE', 'BG', 'CY', 'CZ', 'DE', 'DK', 'EE', 'EL', 'ES', 'FI','FR', 'HR', 'HU', 'IE', 'IT', 'LT','LU', 'LV', 'MT','NL', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK']

#create a dataframe for the results
results_compiled = pd.DataFrame()


import numpy as np
#loop to calculate values for years
for j in range (2011,2019):
    year=j
    #we transpose the values for the year selected
    for i in range (year,year+1):
        df_target = pd.pivot_table(df_selection, values=i, index=['nace_r2'],columns=["geo"], aggfunc=np.sum, fill_value=0)#reorde
    df_target['sum'] = df_target[cols].sum(axis=1)#sums the columns of the countries to "sum" 
    df_target=df_target.drop(cols, axis=1)#eliminamos las columnas sumadas de países
    df_target.loc[df_target['EU27_2020']==0,'EU27_2020'] = df_target['sum']#now we can locate columns with 0 and make the substitution with the column "sum"
    moddf_target=df_target.drop('sum', axis=1)#we create a new table 
    #add rows C31,... and assign value with the ratio multiplying by the value of position C31_32
    year_ratio=j-2011
    moddf_target.loc['C31'] = ratios_values.iloc[0][year_ratio]*moddf_target.loc['C31_C32','EU27_2020']
    moddf_target.loc['C32'] = ratios_values.iloc[1][year_ratio]*moddf_target.loc['C31_C32','EU27_2020']
    moddf_target.loc['N80'] = ratios_values.iloc[2][year_ratio]*moddf_target.loc['N80-N82','EU27_2020']
    moddf_target.loc['N81'] = ratios_values.iloc[3][year_ratio]*moddf_target.loc['N80-N82','EU27_2020']
    moddf_target.loc['N82'] = ratios_values.iloc[4][year_ratio]*moddf_target.loc['N80-N82','EU27_2020']
    #we eliminate rows C31_C32
    moddf_target = moddf_target.drop(['C31_C32', 'N80-N82'])
    pd.set_option('display.float_format', lambda x: '%.4f' % x)
    #cargamos los pesos en el dataframe weight  
    weights_target = pd.read_excel("ecosystemweights.xlsx")
    weights_target.set_index('NACE_R2', inplace=True)#nace como índice
    column_name=str(variable_of_interest)+str(year)
    weights_target[variable_of_interest]=weights_target.index.map(moddf_target['EU27_2020'])#busca en df_target el nace y copia el valor de EU27_2020 en la fila del nace the weights_target
    #creamos la matriz de resultados
    results=weights_target
    for i in range(0,14):
        results.iloc[:, i]=weights_target.iloc[:, i]*weights_target[variable_of_interest]#we multiply the total value added by the weight for each nace
    results.loc['total'] = results.select_dtypes(pd.np.number).sum() #we add the values of each colum in a row call total
    results_compiled[column_name]=results.loc['total']
results_compiled = results_compiled.drop(variable_of_interest)
#sum of the totals
results_SMEs = results_compiled.copy()  
results_big = results_compiled.copy()
#results_compiled.loc['total'] = results_compiled.select_dtypes(pd.np.number).sum()
results_compiled

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:38: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

,"Greenhouse gases (CO2, N2O in CO2 equivalent, CH4 in CO2 equivalent, HFC in CO2 equivalent, PFC in CO2 equivalent, SF6 in CO2 equivalent, NF3 in CO2 equivalent)2011","Greenhouse gases (CO2, N2O in CO2 equivalent, CH4 in CO2 equivalent, HFC in CO2 equivalent, PFC in CO2 equivalent, SF6 in CO2 equivalent, NF3 in CO2 equivalent)2012","Greenhouse gases (CO2, N2O in CO2 equivalent, CH4 in CO2 equivalent, HFC in CO2 equivalent, PFC in CO2 equivalent, SF6 in CO2 equivalent, NF3 in CO2 equivalent)2013","Greenhouse gases (CO2, N2O in CO2 equivalent, CH4 in CO2 equivalent, HFC in CO2 equivalent, PFC in CO2 equivalent, SF6 in CO2 equivalent, NF3 in CO2 equivalent)2014","Greenhouse gases (CO2, N2O in CO2 equivalent, CH4 in CO2 equivalent, HFC in CO2 equivalent, PFC in CO2 equivalent, SF6 in CO2 equivalent, NF3 in CO2 equivalent)2015","Greenhouse gases (CO2, N2O in CO2 equivalent, CH4 in CO2 equivalent, HFC in CO2 equivalent, PFC in CO2 equivalent, SF6 in CO2 equivalent, NF3 in CO2 equivalent)2016","Greenhouse gases (CO2, N2O in CO2 equivalent, CH4 in CO2 equivalent, HFC in CO2 equivalent, PFC in CO2 equivalent, SF6 in CO2 equivalent, NF3 in CO2 equivalent)2017","Greenhouse gases (CO2, N2O in CO2 equivalent, CH4 in CO2 equivalent, HFC in CO2 equivalent, PFC in CO2 equivalent, SF6 in CO2 equivalent, NF3 in CO2 equivalent)2018"
Aerospace & Defence,28226242.4920,29148389.2802,29110583.9126,26739829.6638,27417395.0372,28111763.4713,28329026.5193,28779086.1456
Agri-food,559106926.0932,556322477.1691,558702435.4492,562248964.3920,564000878.6113,568733715.0289,575327870.9117,571829812.8813
Construction,100741915.5988,97347085.5214,95736568.9119,90869813.7920,92192736.4806,92303338.0234,94137918.1692,95633922.6390
Cultural and Creative Industries,21028030.2188,20202140.7483,20038766.2265,17118411.7756,17423710.2441,17904483.9581,18573368.6157,18158463.1032
Digital,15981501.1206,15846030.1463,15724270.3927,13281243.7829,13884222.2431,13811344.7797,14188372.7233,13991851.2178
Electronics,7596660.8037,7386508.4110,7282247.0559,6626404.7511,6932237.4601,7073034.4436,7193258.3337,7158309.9613
Energy - Renewables,334627384.5144,330846128.6029,314289517.5682,297333934.6359,299862884.9905,294231421.4133,293461185.1754,276667002.3725
Energy Intensive Industries,754685606.6705,721318479.8665,695343041.5133,688451889.0530,688701328.6771,687224613.9179,700799353.3388,696653741.0467
Health,50587431.1205,50592740.0784,53497220.2636,50311961.2730,51013215.9560,52015843.0575,51846883.8704,52311014.4227
Mobility - Transport - Automotive,235266412.5728,231871985.9659,223128034.4370,211590873.7861,229078404.5058,229363706.1908,244598043.0254,249571972.1110
"Proximity, Social Economy and Civil Security",37005541.3592,36152582.3041,37553204.3047,37240844.0950,38190976.1830,38643499.4554,38635887.0775,37789913.3650
Retail,108337032.0309,107223619.6781,107524764.1856,102913469.7130,102896049.4645,101832507.5105,102817782.8550,99651581.6814
Textile,10399423.3478,9876745.3535,10286646.1898,9501873.7921,10026119.4451,10006945.7764,10414561.5392,10373994.9158
Tourism,253913829.0532,247921566.6550,244444697.6013,240465011.3678,252152221.9138,259825750.4443,268595613.5377,274574192.0535

In [16]:
#results.to_excel('df_target.xlsx')

In [17]:
#save to file
filename = "%s.xlsx" % variable_of_interest
results_compiled.to_excel(filename)